packages:
  - client
  - server
allowBuilds:
  bcrypt: true
  core-js: true
  core-js-pure: true
  esbuild: true
  msw: true
onlyBuiltDependencies:
  - bcrypt
  - core-js
  - core-js-pure
  - esbuild
  - msw
